name: descriptive-workflow-name
# This workflow is triggered on pushes to the repository.
#on: [push] # aqui decido que clase de eventos va a verificar mi job, puede ser push, pull request,scheduled event begins, external event occurs.
on:
  push:
    branches:
      - master
 
 #schedule:se puede colocar un schedelue para que se ejecute el job cada 5 min
   # - cron:  '0 * * * *'
jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'